# infra/local/docker-compose.yaml

version: "3.8"

services:
  local-db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: score
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
  local-db-migrate:
    image: flyway/flyway:latest
    restart: always
    environment:
      - FLYWAY_DB_URL=jdbc:mysql://local-db/score?allowPublicKeyRetrieval=true&useSSL=false
      - FLYWAY_DB_USER=root
      - FLYWAY_DB_PASSWORD=password
    command: migrate
    volumes:
      - ../../db/flyway.conf:/flyway/conf/flyway.conf
      - ../../db/migration:/flyway/sql